task:
  only_if: $CIRRUS_BRANCH == 'ci'
  skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 300m
  container:
    image: archlinux:base-devel
    cpu: 8
    memory: 32G

  Install_dependencies_script:
    - pacman -Syyuu --noconfirm
    - pacman -Syyuu --noconfirm bash curl git jq python sudo wget tree
    - useradd -s /bin/bash -m builder
    - echo 'builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    - |
      su - builder -c /bin/bash <<SCRIPT
      cd /home/builder
      git clone --depth=1 https://aur.archlinux.org/paru-git.git
      pushd paru-git
      makepkg -sic --noconfirm
      popd
      rm -rf paru-git
      paru -Syu --noconfirm jdk-temurin android-ndk
      SCRIPT
  
  Generate_script:
    - |
      su - builder -c /bin/bash <<SCRIPT
      cd /home/builder
      source /etc/profile
      ls \$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
      git clone -b ci https://github.com/aldrin1127/gs-suspicion-aosp.git
      cd gs-suspicion-aosp
      for i in aosp twrp; do
        ./generate.sh \$i
      done
      SCRIPT
